openapi: 3.0.0
servers:
  - url: https://authdev01.cttexpress.local:443
    description: ''
info:
  version: 65d161da-c99a-4843-9cca-ae22022759b0
  title: TestAWSCognitoFacade
  description: >-
    Acceso securizado vía API REST directo a las operaciones expuestas por el API de AWS Cognito  
    para la gestion administritativa de usuarios.
    User Pool de Pruebas `uat-client-web-pool` en AWS Cognito en Irlanda (`eu-west-1`)
paths:
  /admin/healthcheck:
    get:
      summary: Comprobar que la aplicación esta activa (health-check)
      operationId: GEThealthcheck
      parameters:
        - $ref: '#/components/parameters/Accept'
      responses:
        '200':
          description: HealthCheck Sucessful Response
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/200-HealthCheck-response'
              example:
                cttsimpleawscognitofacade:
                  healthy: true
                deadlocks:
                  healthy: true
      tags:
        - HealthCheck
  /awscognitofacade/simple/v1/rpc-force-user-password-reset/{user_email}:
    post:
      security:
        - basic: []
      summary: Force User Password Reset (RPC Style)  
      operationId: POST/rpc-force-user-password-reset/{user_email}
      parameters:
        - $ref: '#/components/parameters/user_email'
        - $ref: '#/components/parameters/Accept'
      responses:
        '204':
          description: 'The operation requested was successful (NO Body Content is returned)'
        '401':
          description: UNAUTHORIZED (invalid or missing Basic Auth credentials)
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/common-error-response' 
              examples:
                sample401-01:
                  $ref: '#/components/examples/sample401-01'
      tags:
        - AdminUserTasks
  /awscognitofacade/simple/v1/rpc-disable-user/{user_email}:
    post:
      security:
        - basic: []    
      summary: Disable User (RPC Style)
      operationId: POST/rpc-disable-user/{user_email}
      parameters:
        - $ref: '#/components/parameters/user_email'
        - $ref: '#/components/parameters/Accept'
      responses:
        '204':
          description: 'The operation requested was successful (NO Body Content is returned)'
        '401':
          description: UNAUTHORIZED (invalid or missing Basic Auth credentials)
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/common-error-response' 
              examples:
                sample401-01:
                  $ref: '#/components/examples/sample401-01'
      tags:
        - AdminUserTasks
  /awscognitofacade/simple/v1/rpc-enable-user/{user_email}:
    post:
      security:
        - basic: []
      summary: Enable User (RPC Style)
      operationId: POST/rpc-enable-user/{user_email}
      parameters:
        - $ref: '#/components/parameters/user_email'
        - $ref: '#/components/parameters/Accept'
      responses:
        '204':
          description: 'The operation requested was successful (NO Body Content is returned)'
        '401':
          description: UNAUTHORIZED (invalid or missing Basic Auth credentials)
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/common-error-response' 
              examples:
                sample401-01:
                  $ref: '#/components/examples/sample401-01'
      tags:
        - AdminUserTasks
  /awscognitofacade/simple/v1/rpc-delete-user/{user_email}:
    post:
      security:
        - basic: []    
      summary: Delete User (RPC Style)
      operationId: POST/rpc-delete-user/{user_email}
      parameters:
        - $ref: '#/components/parameters/user_email'
        - $ref: '#/components/parameters/Accept'
      responses:
        '204':
          description: 'The operation requested was successful (NO Body Content is returned)'
        '401':
          description: UNAUTHORIZED (invalid or missing Basic Auth credentials)
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/common-error-response' 
              examples:
                sample401-01:
                  $ref: '#/components/examples/sample401-01'
      tags:
        - AdminUserTasks
  /awscognitofacade/simple/v1/rpc-retrieve-user-metadata/{user_email}:
    post:
      security:
        - basic: []    
      summary: Retrieve User Metadata (RPC Style)
      operationId: POST/rpc-retrieve-user-metadata/{user_email}
      parameters:
        - $ref: '#/components/parameters/user_email'
        - $ref: '#/components/parameters/Accept'
      responses:
        '200':
          description: 'Metadatos del usuario'
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/200-Retrieve-User-Metadata-response' 
        '401':
          description: UNAUTHORIZED (invalid or missing Basic Auth credentials)
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/common-error-response' 
              examples:
                sample401-01:
                  $ref: '#/components/examples/sample401-01'
      tags:
        - AdminUserTasks
  /awscognitofacade/simple/v1/rpc-update-user-attributes/{user_email}:
    post:
      security:
        - basic: []    
      summary: Update User Attributes (RPC Style)
      operationId: POST/rpc-update-user-attributes/{user_email}
      parameters:
        - $ref: '#/components/parameters/user_email'
        - $ref: '#/components/parameters/Accept'
        - $ref: '#/components/parameters/Content-Type'
      responses:
        '204':
          description: 'The operation requested was successful (NO Body Content is returned)'
        '401':
          description: UNAUTHORIZED (invalid or missing Basic Auth credentials)
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/common-error-response' 
              examples:
                sample401-01:
                  $ref: '#/components/examples/sample401-01' 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - phone_number
              properties:
                name:
                  description: 'Nombre y Apellidos del Usuario'
                  type: string
                  minLength: 5
                  maxLength: 64
                  example: Pablo SanchoSopranis Sampol
                phone_number:
                  description: 'Teléfono del Usuario'
                  type: string
                  minLength: 12
                  maxLength: 13
                  pattern: '^\\+\\d{11,12}$'
                  example: '+34666777888'
                custom_attributes:
                  type: object
                  properties:
                    custom:ctt_client_code:
                      type: string
                      example: 'TECHEDGE-01a'
                    custom:ctt_agency_code:
                      type: string
                      example: 'TECHEDGE-01b'
      tags:
        - AdminUserTasks
  /awscognitofacade/simple/v1/rpc-update-user-custom-attributes/{user_email}:
    post:
      security:
        - basic: []    
      summary: Update User Custom Attributes only (RPC Style).
      operationId: POST/rpc-update-user-custom-attributes/{user_email}
      parameters:
        - $ref: '#/components/parameters/user_email'
        - $ref: '#/components/parameters/Accept'
        - $ref: '#/components/parameters/Content-Type'
      responses:
        '204':
          description: 'The operation requested was successful (NO Body Content is returned)'
        '401':
          description: UNAUTHORIZED (invalid or missing Basic Auth credentials)
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/common-error-response' 
              examples:
                sample401-01:
                  $ref: '#/components/examples/sample401-01'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - custom_attributes
              properties:
                custom_attributes:
                  type: object
                  properties:
                    custom:ctt_client_code:
                      type: string
                      example: 'TECHEDGE-01a'
                    custom:ctt_agency_code:
                      type: string
                      example: 'TECHEDGE-01b'
      tags:
        - AdminUserTasks
  /awscognitofacade/simple/v1/rpc-create-user:
    post:
      security:
        - basic: []    
      summary: Create a New User (RPC Style)
      operationId: POST/rpc-create-user
      parameters:
        - $ref: '#/components/parameters/Accept'
        - $ref: '#/components/parameters/Content-Type'
      responses:
        '204':
          description: 'The operation requested was successful (NO Body Content is returned)'
        '401':
          description: UNAUTHORIZED (invalid or missing Basic Auth credentials)
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/common-error-response' 
              examples:
                sample401-01:
                  $ref: '#/components/examples/sample401-01'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - name
                - phone_number
              properties:
                email:
                  type: string
                  pattern: '^\\+\\d{11,12}$'
                  description: 'eMail del Usuario (debe ser un eMail válido)'
                  example: psanchosopranis@gmail.com
                name:
                  description: 'Nombre y Apellidos del Usuario'
                  type: string
                  minLength: 5
                  maxLength: 64
                  example: Pablo SanchoSopranis Sampol
                phone_number:
                  description: 'Teléfono del Usuario'
                  type: string
                  minLength: 12
                  maxLength: 13
                  pattern: '^\\+\\d{11,12}$'
                  example: '+34666777888'
                custom_attributes:
                  type: object
                  properties:
                    custom:ctt_client_code:
                      type: string
                      example: 'TECHEDGE-01a'
                    custom:ctt_agency_code:
                      type: string
                      example: 'TECHEDGE-01b'
      tags:
        - AdminUserTasks
components:
  parameters:
    Accept:
      name: Accept
      in: header
      required: true
      style: simple
      schema:
        type: string
        example: application/json
    user_email:
      name: user_email
      in: path
      required: true
      style: simple
      schema:
        type: string
        pattern: '^\\+\\d{11,12}$'
        description: 'eMail del Usuario (debe ser un eMail válido)'
        example: psanchosopranis@gmail.com
    Content-Type:
      name: Content-Type
      in: header
      required: true
      style: simple
      schema:
        type: string
        example: application/json
  schemas:
    '200-HealthCheck-response':
      type: object
      properties:
        cttsimpleawscognitofacade:
          type: object
          description: 'App Status'
          properties:
            healthy:
              type: boolean
        deadlocks:
          type: object
          description: 'Deadlocks Status'
          properties:
            healthy:
              type: boolean
    '200-Retrieve-User-Metadata-response':
      type: object
      properties:
        user_id:
          type: string
          example: 'e3b75952-bc4e-4cab-bb0b-1b97d378b18d'
        user_status:
          type: string
          example: 'CONFIRMED'
        user_is_enabled:
          type: boolean
          example: true,
        user_create_date:
          type: string
          example: 'Mon Aug 16 15:18:07 CEST 2021'
        user_last_modified_date:
          type: string
          example: 'Mon Aug 16 17:57:57 CEST 2021'
        user_attributes: 
          type: object
          properties:
            sub:
              type: string
              example: 'e3b75952-bc4e-4cab-bb0b-1b97d378b18d'
            email:
              type: string
              example: 'psanchosopranis@gmail.com'
            email_verified:
              type: boolean
              example: true
            name:
              type: string
              example: 'Pablo Sancho-Sopranis Sampol'
            phone_number_verified:
              type: boolean
              example: true
            phone_number:
              type: string
              example: '+34650711077'
            custom:ctt_agency_code:
              type: string
              example: 'TECHEDGE-01a'
            custom:ctt_client_code:
              type: string
              example: 'TECHEDGE-01b'          
    'common-error-response':
      type: object
      properties:
        errorId:
          type: string
          description: 'Identificador del Error'
        errorAlias:
          type: string
          description: 'Identificador (alias) del Error'
        errorMessages:
          type: array 
          description: 'Lineas con información adicionales de la(s) condicion(es) de error.'
          items:
            type: string
  examples:
    sample401-01:
      summary: 'ERR-401-UNAUTHORIZED'
      value:
        errorId: 'ERR-401-UNAUTHORIZED'
        errorAlias": 'invalid-or-missing-credentials'
        errorMessages": 
        - 'Se requieren credenciales válidas (y activas) para acceder a este recurso.'
  securitySchemes:
    basic:
      type: http
      scheme: basic


